name-template: '$RESOLVED_VERSION 🌈'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feat'
      - 'feature'
      - 'enh'
      - 'enhancement'
      - 'imp'
      - 'improvement'
  - title: '📖 Documentation'
    labels:
      - 'docs'
      - 'documentation'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🏗️ Infrastructure'
    labels:
      - 'infra'
      - 'infrastructure'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'ci'
      - 'refactor'
      - 'perf'
  - title: '🧪 Tests'
    labels:
      - 'test'
      - 'testing'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## What's New

  $CHANGES